### PR TITLE
Send PUBACK when receiving a publish with qos > 0

### PR DESCRIPTION
**Pull request by johanneswuerbach**
I'm not sure, why https://github.com/njh/ruby-mqtt/pull/56 was closed. This PR is based on the code from @antico5 and I added an additional test

### CODE REVIEW

**Comment by antico5** [comment]
I closed it (don't remember why) and forgot to update this :) thanks for adding a test!

**Comment by levent** [comment]
This is great. I'm glad I checked the open PRs before attempting to fix this myself.

**Comment by njh** [comment]
Sorry, for not merging this yet. Going to review it in the next couple of days.

**Comment by tindaio** [comment]
Hello is there already merge to the master?

**Pull request merged**
