### PR TITLE
Add the ability to ignore retained packets when subscribed.

### PR DESCRIPTION
**Pull request by jasiek**

### CODE REVIEW

**Comment by njh** [comment]
Looks like a good addition, thanks.

But I wonder if the parameter should be a hash of options?
So that when reading the code, it is clear what the ```get('topic/name', true)``` means?

Something like this?

```ruby
get('topic/name', :omit_retained => false)
```

**Comment by jasiek** [comment]
That makes sense. I reckon Ruby 2's keyword params would be even nicer, but that's a separate PR.

**Comment by njh** [comment]
Note that I am currently attempting to support old versions of ruby in this gem.

Having worked in an environment that uses RHEL/CentOS, it can be very helpful if it works with old versions of ruby.

**Comment by jasiek** [comment]
Fair enough.

**Comment by jasiek** [comment]
Updated.

**Comment by njh** [comment]
Thanks!

**Pull request merged**
